// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYBX0mOvL0FGyDfbm8-QWz4F75jNPLI6U',
    appId: '1:880069600603:android:a5585a2886231b56d4667e',
    messagingSenderId: '880069600603',
    projectId: 'khidma-109d5',
    storageBucket: 'khidma-109d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNFI3xyD9eBt1NZXB0kZ5FzNdBEevXm1A',
    appId: '1:880069600603:ios:613d1bc35aa2d123d4667e',
    messagingSenderId: '880069600603',
    projectId: 'khidma-109d5',
    storageBucket: 'khidma-109d5.appspot.com',
    androidClientId: '880069600603-o1akg19htpp2pnck77qcv8a0500q9mib.apps.googleusercontent.com',
    iosClientId: '880069600603-ndh7lf9cn312u6oekv0uh94kb3nrkjc6.apps.googleusercontent.com',
    iosBundleId: 'com.example.khidmaArtisanFlutter',
  );
}
